### PR TITLE
makes sidebar info not show up if blank

### PR DESCRIPTION
**Pull request by straleyb**
I don't know if we wanted to add another method to the solr_document class to do these checks, but that can be done if needed.

### CODE REVIEW

**Comment by terrellt** [comment]
This isn't great. How does index_default decide which fields to show? Do they differ?

**Comment by straleyb** [comment]
Index default uses #should_render_index_field? to look at what is configured in blacklight to be viewed in the index view. What I can do is bring in those functions in and use them in the side panel view since I think we want to display the same information there as we do in the index view.

**Comment by straleyb** [comment]
So the implementation is the same as index. Now I could go further and extract the index fields block into a partial and just render the partial in the two places. Sound right?

**Comment by straleyb** [comment]
Ill rebase

**Pull request merged**
