### PR TITLE
Added more sort fields

### PR DESCRIPTION
**Pull request by straleyb**
@terrellt Do we want to do the alphabetical and reverse alphabetical sort as well?

### CODE REVIEW

**Comment by terrellt** [comment]
Do we even want these ones? I'm not sure how relevant they are to the goal of building discovery

**Comment by straleyb** [comment]
The only thing I could really think of is maybe people want to see what the oldest building in the database is. Or newest for that matter. The recently added though is probably useless in the context of building discovery.

**Comment by straleyb** [comment]
Should we close this PR and issue #108 ?

**Comment by terrellt** [comment]
I don't know. @mellinma ?

**Comment by terrellt** [comment]
@mellinma says Relevance/Title A-Z/Title Z-A

**Comment by straleyb** [comment]
Fixes #108

**Pull request merged**
