### PR TITLE
adds padding around navbar and Tools sidebar color

### LINKED ISSUE #69: add padding to top of facets
make the facets line up with either the page title or the map

### LINKED ISSUE #71: Add padding to the bottom of the header
Add some padding to the bottom of the header so that the content isn't right after it

### LINKED ISSUE #72: show view "Tools" sidebar
At the bottom of the "Tools" sidebar there is a random row that is colored yellow. We should get rid of this and probably change the heading to yellow to keep it consistent with the index view

### PR DESCRIPTION
**Pull request by balesh2**
Fixes #69 
Fixes #71 
Fixes #72

### CODE REVIEW

**Comment by straleyb** [comment]
@balesh2 How do these look on the mobile side of things?

**Comment by balesh2** [comment]
It mostly looks good in mobile. I'm going to make one change though

**Comment by terrellt** [comment]
@balesh2 @straleyb Ready to merge?

**Comment by balesh2** [comment]
@terrellt yes. Unless @straleyb has any objection, I'll just make a new issue for getting rid of the "tools" sidebar

**Pull request merged**
