### PR TITLE
Added object for importing lat longs and configured map to display

### PR DESCRIPTION
**Pull request by straleyb**
indexed lat longs

### CODE REVIEW

**Comment by straleyb** [comment]
@balesh2 review. It finally passed after I fixed stuff and didn't push a million commits at the same time.

**Comment by straleyb** [comment]
@terrellt Helena already saw this and reviewed it. I had to remake it because I broked everything. Can you review?

**Comment by balesh2** [comment]
:+1: for not breaking github

**Comment by straleyb** [comment]
@terrellt Can we get this reviewed please?

**Pull request merged**
