### PR TITLE
Feature/search bar

### PR DESCRIPTION
**Pull request by straleyb**
Relates #39. I added the searchbar back into the navbar on mobile and aligned it with the OSU and UO logos for symmetry. Also I added a javascript function that toggles the glyphicon on the button to point in the direction the slideout menu will slide on next button press.

### CODE REVIEW

**Comment by balesh2** [comment]
:+1:

**Comment by straleyb** [comment]
@terrellt The search bar trickery that I had done broke after update as well as the full screen navbar stuff. So don't merge this yet. Im going through and fixing layout and making sure it looks good across the board.

**Comment by straleyb** [comment]
Ok, this should be back to the way it was previously now.

**Comment by straleyb** [comment]
@terrellt Can this be reviewed so the new changes can be set in place?

**Pull request merged**
