### PR TITLE
Fixes metadata alignment to be closer to picture

### LINKED ISSUE #121: Long descriptions should not run off the page
On this page, the material description runs off the side of the page when the viewport is 1400px wide:

http://building-oregon-dev.library.oregonstate.edu/?page=1&per_page=100&q=%22fish+lake+guard%22&search_field=all_fields&sort=score+desc&view=list

screen shot 2015-04-27 at 3 38 58 pm

### PR DESCRIPTION
**Pull request by straleyb**
Fixes #121. Metadata needed to be moved to the left quite a bit.

### CODE REVIEW

**Comment by terrellt** [comment]
Can't you just remove the wrapping "container" class?

**Comment by straleyb** [comment]
Lets find out!

**Comment by terrellt** [comment]
Needs rebased, but did that work?

**Comment by straleyb** [comment]
Yeah it did. Im rebasing now. I didn't know container would have that effect on the elements within it. Blew my mind a little. I thought it was supposed to encase things within padding/margins and whatnot

**Comment by straleyb** [comment]
@terrellt this keeps failing when trying to install byebug. Says we need ruby version 2.0.0.

**Comment by terrellt** [comment]
@straleyb Yeah, there's no CircleCI configuration. You'd have to merge the CircleCI branch and rebase if you want it to pass.

**Pull request merged**
